"""Bounded reader and analysis splitter for published Simra schematic artifacts.

Simra publishes one compiled schematic as a directory containing a
``schematic.artifact.json`` descriptor, a ``design.spice`` deck, and a
``schematic.simra.json`` typed view. The descriptor carries SHA-256 digests for
every published file and a ``validation`` block whose ``simulation_handoff``
value states whether the emitted deck carries one analysis (``direct``) or more
than one (``split_required``).

This module owns the native-format binding only: it validates the descriptor,
verifies the published digests against the bytes on disk, recovers the typed
``testbench`` declaration from the view, and derives one single-analysis deck
per declared analysis. It runs no simulator and makes no engineering claim.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import importlib
import json
import math
import os
from pathlib import Path
import re
import stat
import sys
from typing import Any, Callable, Mapping, NoReturn

from ..contract import (
    FileRecordError,
    FileRecordLimitError,
    bounded_text,
    file_record,
    stable_regular_file,
)


ARTIFACT_SCHEMA = "simra.schematic-artifact/v2"
VIEW_SCHEMA = "simra.schematic/v2"

MAX_DESCRIPTOR_BYTES = 4 * 1024 * 1024
MAX_SOURCE_BYTES = 64 * 1024 * 1024
MAX_VIEW_BYTES = 64 * 1024 * 1024
MAX_DECK_BYTES = 16 * 1024 * 1024
MAX_CDL_BYTES = 16 * 1024 * 1024
MAX_MODELS_BYTES = 16 * 1024 * 1024
MAX_ANALYSES = 16
MAX_SAVED_NETS = 1_024
MAX_UNRESOLVED_EXAMPLES = 20
MAX_UNRESOLVED_TOKEN_DISPLAY_CHARS = 256
MAX_UNRESOLVED_MESSAGE_CHARS = 3_500
MAX_DIAGNOSTIC_NAME_CHARS = 128

SUPPORTED_ANALYSIS_KINDS = ("op", "dc", "ac", "tran")
SUPPORTED_HANDOFFS = ("direct", "split_required")

#: Every top-level analysis card ngspice recognizes, not only the supported
#: subset. An unsupported card in a published deck must be reported, never
#: silently dropped while splitting.
ANALYSIS_CARD_RE = re.compile(
    r"^\s*\.(op|dc|ac|tran|noise|hb|tf|pz|sens|sp|disto)\b",
    re.IGNORECASE,
)
UNRESOLVED_TOKEN_RE = re.compile(
    rf"(?<![A-Za-z0-9_])"
    rf"SIMRA_UNRESOLVED_[A-Za-z0-9_]+"
    rf"(?![A-Za-z0-9_])"
)
_SUBCKT_CELL_RE = re.compile(r"^\s*\.subckt\s+(?P<cell>\S+)", re.IGNORECASE)
_SUBCKT_DECLARATION_RE = re.compile(
    r"^\s*\.subckt[ \t]+(?P<cell>\S+)(?P<ports>[^\r\n]*)$",
    re.IGNORECASE,
)
_ENDS_RE = re.compile(r"^\s*\.ends(?:\s|$)", re.IGNORECASE)
#: Directives that would make a composed model prelude non-self-contained or
#: would terminate/redirect the deck the shared simulation profile inspects.
MODELS_FORBIDDEN_RE = re.compile(
    r"^\s*\.(inc|include|lib|control|endc|end|title|measure|meas|print|four|fft|step|op|dc|ac|tran)\b",
    re.IGNORECASE,
)
#: XSPICE code-model types whose model cards reach OUTSIDE the deck: they
#: load an executable shared object (d_cosim), spawn a process (d_process),
#: or read state/stimulus files (d_source, d_state, filesource,
#: multi_input_pwl, table2d/3d). In the self-contained model-library role
#: these are collateral escapes, not model cards, and are refused unless the
#: exact card was generated by a reviewed, digest-pinned block composition
#: (the caller then names each generated model, and the composition digest
#: check guarantees the bytes are the reviewed ones).
EXECUTABLE_MODEL_TYPES = frozenset(
    {
        "d_cosim",
        "d_process",
        "d_source",
        "d_state",
        "filesource",
        "multi_input_pwl",
        "table2d",
        "table3d",
    }
)
#: The ONLY executable model type a reviewed block composition ever
#: generates. The allowance is exact in both name and type, so a permitted
#: name can never admit a process- or file-backed model instead.
PERMITTED_EXECUTABLE_MODEL_TYPE = "d_cosim"
_MODEL_CARD_RE = re.compile(
    r"^\s*\.model\s+(?P<name>\S+)\s+(?P<type>[a-z_][a-z0-9_]*)", re.IGNORECASE
)
_PATH_COMPONENT_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_NET_NAME_RE = re.compile(r"^[A-Za-z0-9_.:+$\[\]-]{1,256}$")
_DIAGNOSTIC_NAME_RE = re.compile(r"^[A-Za-z0-9_.:+-]+$")
_DIAGNOSTIC_KIND_RE = re.compile(r"^[a-z][a-z0-9_]{0,31}$")
_DIAGNOSTIC_PARAMETER_RE = re.compile(r"^[A-Z0-9_]{1,64}$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_SAFE_SPICE_TOKEN_RE = re.compile(r"^[A-Za-z0-9_.:+-]+$")

_SCHEMATIC_DIGEST_KEYS = (
    "descriptor_sha256",
    "source_sha256",
    "view_sha256",
    "netlist_sha256",
    "cdl_sha256",
)
_INDEPENDENT_SOURCE_KINDS = frozenset(
    ("vdc", "idc", "vpulse", "ipulse", "vsin", "isin", "vpwl", "ipwl")
)
_DEVICE_SPICE_PREFIX = {
    "nmos": "M",
    "pmos": "M",
    "resistor": "R",
    "capacitor": "C",
    "inductor": "L",
    "ground": "V",
    "vdc": "V",
    "idc": "I",
    "vpulse": "V",
    "ipulse": "I",
    "vsin": "V",
    "isin": "I",
    "vpwl": "V",
    "ipwl": "I",
    "vcvs": "E",
    "vccs": "G",
    "cell": "X",
    "abstract_block": "X",
}
_DEVICE_TERMINALS = {
    "nmos": ("D", "G", "S", "B"),
    "pmos": ("D", "G", "S", "B"),
    "resistor": ("P", "M"),
    "capacitor": ("P", "M"),
    "inductor": ("P", "M"),
    "ground": ("P",),
    "vdc": ("P", "M"),
    "idc": ("P", "M"),
    "vpulse": ("P", "M"),
    "ipulse": ("P", "M"),
    "vsin": ("P", "M"),
    "isin": ("P", "M"),
    "vpwl": ("P", "M"),
    "ipwl": ("P", "M"),
    "vcvs": ("P", "M", "CP", "CM"),
    "vccs": ("P", "M", "CP", "CM"),
}
_STRUCTURAL_PARAMETER_KEYS = {
    "nmos": frozenset(("model", "w", "l", "m", "nf")),
    "pmos": frozenset(("model", "w", "l", "m", "nf")),
    "resistor": frozenset(("r",)),
    "capacitor": frozenset(("c", "ic")),
    "inductor": frozenset(("l",)),
    "vcvs": frozenset(("gain",)),
    "vccs": frozenset(("gain",)),
}

# This is the exact required-parameter vocabulary used by Simra's
# ``contract_v2.lifecycle_v2``. Keep the lifecycle implementation below
# standalone: an installed OpenADA package must not depend on a sibling Simra
# source checkout merely to verify a published bundle.
_LIFECYCLE_REQUIRED_PARAMETERS = {
    "nmos": frozenset(("model", "w", "l", "m", "nf")),
    "pmos": frozenset(("model", "w", "l", "m", "nf")),
    "resistor": frozenset(("r",)),
    "capacitor": frozenset(("c",)),
    "inductor": frozenset(("l",)),
    "ground": frozenset(),
    "vdc": frozenset(("dc",)),
    "idc": frozenset(("dc",)),
    "vpulse": frozenset(
        (
            "initial_value",
            "pulsed_value",
            "delay_time",
            "rise_time",
            "fall_time",
            "pulse_width",
            "period",
        )
    ),
    "ipulse": frozenset(
        (
            "initial_value",
            "pulsed_value",
            "delay_time",
            "rise_time",
            "fall_time",
            "pulse_width",
            "period",
        )
    ),
    "vsin": frozenset(("dc", "amplitude", "freq", "delay", "damping")),
    "isin": frozenset(("dc", "amplitude", "freq", "delay", "damping")),
    "vpwl": frozenset(("dc", "points")),
    "ipwl": frozenset(("dc", "points")),
    "vcvs": frozenset(("gain",)),
    "vccs": frozenset(("gain",)),
}


class SimraArtifactError(Exception):
    """One bounded, typed reason a published artifact cannot be dispatched."""

    def __init__(self, code: str, message: str, *, hint: str | None = None) -> None:
        self.code = code
        self.message = message
        self.hint = hint
        super().__init__(message)


@dataclass(frozen=True, slots=True)
class _UnresolvedPlaceholder:
    token: str
    cell_name: str | None


@dataclass(frozen=True, slots=True)
class DerivedDeck:
    """One single-analysis deck derived from a published multi-analysis deck."""

    index: int
    kind: str
    analysis: dict[str, Any]
    text: str
    sha256: str


@dataclass(frozen=True, slots=True)
class SimraTestbench:
    """One validated, digest-bound Simra testbench artifact."""

    descriptor_path: Path
    directory: Path
    identifier: str
    label: str
    top: str
    netlist_path: Path
    view_path: Path
    analyses: tuple[dict[str, Any], ...]
    saved_nets: tuple[str, ...]
    simulation_handoff: str
    parameters_state: str
    #: Simra's ``validation.simulation_ready``: the deck runs with no external
    #: model collateral. False for every MOS testbench by construction.
    self_contained: bool
    netlist_sha256: str
    view_sha256: str
    source_sha256: str
    deck_text: str
    input_records: tuple[dict[str, Any], ...] = field(default=())

    @property
    def dispatch_mode(self) -> str:
        return "split" if len(self.analyses) > 1 else "direct"


@dataclass(frozen=True, slots=True)
class SimraSchematicBundle:
    """One immutable, five-file snapshot of a promoted schematic-only DUT."""

    descriptor_path: Path
    source_path: Path
    view_path: Path
    netlist_path: Path
    cdl_path: Path
    directory: Path
    identifier: str
    label: str
    top: str
    port_order: tuple[str, ...]
    design_subckt_names: tuple[str, ...]
    lifecycle: dict[str, Any]
    descriptor_document: dict[str, Any]
    view_document: dict[str, Any]
    descriptor_bytes: bytes
    source_bytes: bytes
    view_bytes: bytes
    netlist_bytes: bytes
    cdl_bytes: bytes
    descriptor_text: str
    source_text: str
    view_text: str
    netlist_text: str
    cdl_text: str
    descriptor_sha256: str
    source_sha256: str
    view_sha256: str
    netlist_sha256: str
    cdl_sha256: str
    descriptor_record: dict[str, Any]
    source_record: dict[str, Any]
    view_record: dict[str, Any]
    netlist_record: dict[str, Any]
    cdl_record: dict[str, Any]
    input_records: tuple[dict[str, Any], ...] = field(default=())

    @property
    def bundle_digests(self) -> dict[str, str]:
        """Return the exact digest vocabulary used by ``dut.bundle``."""

        return {
            "descriptor_sha256": self.descriptor_sha256,
            "source_sha256": self.source_sha256,
            "view_sha256": self.view_sha256,
            "netlist_sha256": self.netlist_sha256,
            "cdl_sha256": self.cdl_sha256,
        }


class _DuplicateJsonKey(ValueError):
    pass


def _stat_identity(value: os.stat_result) -> tuple[int, int, int, int, int, int]:
    return (
        value.st_dev,
        value.st_ino,
        value.st_mode,
        value.st_size,
        value.st_mtime_ns,
        value.st_ctime_ns,
    )


def _snapshot_regular_file(
    path: Path,
    *,
    kind: str,
    role: str,
    maximum_bytes: int,
) -> tuple[bytes, str, dict[str, Any]]:
    """Capture one non-symlink regular file exactly once.

    ``stable_regular_file`` verifies the opened file and its resolved path, but
    it resolves before applying ``O_NOFOLLOW``. The artifact contract is
    stricter: the published path itself may not be a symlink. Check that path
    before and after the bounded read, and bind its identity to the descriptor
    opened by the shared stable-file helper.
    """

    try:
        before = path.lstat()
    except FileNotFoundError as exc:
        raise SimraArtifactError(
            "experiment.dut.artifact_missing",
            f"The schematic bundle member is missing: {path}",
        ) from exc
    except OSError as exc:
        raise SimraArtifactError(
            "experiment.dut.artifact_unstable",
            f"The schematic bundle member could not be inspected safely: {path}",
        ) from exc
    if stat.S_ISLNK(before.st_mode):
        raise SimraArtifactError(
            "experiment.dut.artifact_unstable",
            f"The schematic bundle member must not be a symbolic link: {path}",
        )
    if not stat.S_ISREG(before.st_mode):
        raise SimraArtifactError(
            "experiment.dut.artifact_unstable",
            f"The schematic bundle member is not a regular file: {path}",
        )
    if before.st_size > maximum_bytes:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            f"The schematic bundle member exceeds its {maximum_bytes}-byte limit: {path}",
        )

    try:
        with stable_regular_file(path) as (handle, opened):
            if _stat_identity(opened) != _stat_identity(before):
                raise SimraArtifactError(
                    "experiment.dut.artifact_unstable",
                    f"The schematic bundle member changed before capture: {path}",
                )
            raw = handle.read(maximum_bytes + 1)
            if len(raw) > maximum_bytes:
                raise SimraArtifactError(
                    "experiment.dut.bundle_invalid",
                    f"The schematic bundle member exceeds its {maximum_bytes}-byte limit: {path}",
                )
            if len(raw) != opened.st_size:
                raise SimraArtifactError(
                    "experiment.dut.artifact_unstable",
                    f"The schematic bundle member changed during capture: {path}",
                )
    except SimraArtifactError:
        raise
    except FileRecordError as exc:
        raise SimraArtifactError(
            "experiment.dut.artifact_unstable",
            f"The schematic bundle member could not be captured as one stable regular file: {path}",
        ) from exc

    try:
        after = path.lstat()
    except OSError as exc:
        raise SimraArtifactError(
            "experiment.dut.artifact_unstable",
            f"The schematic bundle member changed after capture: {path}",
        ) from exc
    if stat.S_ISLNK(after.st_mode) or _stat_identity(after) != _stat_identity(before):
        raise SimraArtifactError(
            "experiment.dut.artifact_unstable",
            f"The schematic bundle member changed after capture: {path}",
        )

    digest = hashlib.sha256(raw).hexdigest()
    record = {
        "kind": kind,
        "role": role,
        "path": str(path.resolve()),
        "exists": True,
        "bytes": len(raw),
        "sha256": digest,
    }
    return raw, digest, record


def _utf8_text(raw: bytes, *, role: str, path: Path) -> str:
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            f"The schematic {role} is not valid UTF-8: {path}",
        ) from exc


def _json_object(
    text: str,
    *,
    role: str,
    path: Path,
) -> dict[str, Any]:
    def pairs_hook(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        document: dict[str, Any] = {}
        for name, value in pairs:
            if name in document:
                raise _DuplicateJsonKey(name)
            document[name] = value
        return document

    def reject_constant(value: str) -> None:
        raise ValueError(f"non-finite JSON constant {value}")

    try:
        document = json.loads(
            text,
            object_pairs_hook=pairs_hook,
            parse_constant=reject_constant,
        )
    except (_DuplicateJsonKey, json.JSONDecodeError, ValueError) as exc:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            f"The schematic {role} is not one strict JSON document: {path}",
        ) from exc
    if not isinstance(document, dict):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            f"The schematic {role} is not a JSON object: {path}",
        )
    return document


def _schematic_member_path(
    directory: Path,
    value: object,
    *,
    field_name: str,
) -> Path:
    if not isinstance(value, str) or _PATH_COMPONENT_RE.fullmatch(value) is None:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            f"The descriptor {field_name!r} must name one bounded artifact-local file.",
        )
    candidate = directory / value
    if candidate.parent != directory:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            f"The descriptor {field_name!r} must not escape the artifact directory.",
        )
    return candidate


def _validated_expected_digests(
    expected_digests: Mapping[str, str],
) -> dict[str, str]:
    if not isinstance(expected_digests, Mapping):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "dut.bundle must supply the five expected schematic bundle digests.",
        )
    if set(expected_digests) != set(_SCHEMATIC_DIGEST_KEYS):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "dut.bundle must contain exactly descriptor_sha256, source_sha256, "
            "view_sha256, netlist_sha256, and cdl_sha256.",
        )
    normalized: dict[str, str] = {}
    for name in _SCHEMATIC_DIGEST_KEYS:
        value = expected_digests.get(name)
        if not isinstance(value, str) or _SHA256_RE.fullmatch(value) is None:
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                f"dut.bundle.{name} must be one lowercase SHA-256 digest.",
            )
        normalized[name] = value
    return normalized


def _rederive_lifecycle_v2(
    document: dict[str, Any],
    netlist_text: str | None = None,
) -> dict[str, Any]:
    """Standalone copy of Simra ``contract_v2.lifecycle_v2``."""

    unresolved: list[dict[str, str]] = []
    blockers: list[str] = []
    instances = [
        instance
        for cell in document.get("cells", [])
        if isinstance(cell, dict) and isinstance(cell.get("entities"), dict)
        for instance in cell["entities"].get("instances", [])
        if isinstance(instance, dict)
    ]
    for instance in instances:
        name = str(instance.get("name") or instance.get("id") or "?")
        required = _LIFECYCLE_REQUIRED_PARAMETERS.get(instance.get("kind"))
        if required is not None:
            parameters = instance.get("parameters")
            present = set(parameters) if isinstance(parameters, dict) else set()
            for key in sorted(required - present):
                unresolved.append({"instance": name, "parameter": key})
        if instance.get("netlistable") is not True:
            blockers.append(f"instance {name} is not netlistable")
    if document.get("view", {}).get("kind") == "testbench":
        testbench = document.get("testbench")
        if not isinstance(testbench, dict) or not testbench.get("analyses"):
            blockers.append("testbench declares no analyses")
        if not any(instance.get("kind") == "ground" for instance in instances):
            blockers.append("testbench has no ground reference")
    if netlist_text is not None and "SIMRA_UNRESOLVED_" in netlist_text:
        blockers.append("emitted netlist contains unresolved placeholder tokens")
    state = (
        "simulation_candidate"
        if instances and not unresolved and not blockers
        else "display_candidate"
    )
    return {"state": state, "unresolved": unresolved, "blockers": blockers}


def _design_cells(
    view_document: Mapping[str, Any],
) -> tuple[list[Mapping[str, Any]], tuple[str, ...]]:
    cells = view_document.get("cells")
    if not isinstance(cells, list):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The schematic view publishes no cells array.",
        )
    design_cells: list[Mapping[str, Any]] = []
    design_names: list[str] = []
    for cell in cells:
        if not isinstance(cell, Mapping) or cell.get("kind") != "design":
            continue
        name = cell.get("name")
        if (
            not isinstance(name, str)
            or len(name) > 256
            or _SAFE_SPICE_TOKEN_RE.fullmatch(name) is None
        ):
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                "Every design cell must publish one bounded SPICE-safe name.",
            )
        design_cells.append(cell)
        design_names.append(name)
    if not design_cells:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The schematic view publishes no design cell.",
        )
    folded = [name.casefold() for name in design_names]
    if len(folded) != len(set(folded)):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The schematic view publishes colliding design-cell names.",
        )
    return design_cells, tuple(design_names)


def _netlist_subckts(
    netlist_text: str,
) -> tuple[tuple[str, tuple[str, ...]], ...]:
    declarations: list[tuple[str, tuple[str, ...]]] = []
    for line in netlist_text.splitlines():
        match = _SUBCKT_DECLARATION_RE.match(line)
        if match is None:
            continue
        declarations.append(
            (match.group("cell"), tuple(match.group("ports").split()))
        )
    if not declarations:
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The schematic netlist publishes no .SUBCKT declaration.",
        )
    folded = [name.casefold() for name, _ports in declarations]
    if len(folded) != len(set(folded)):
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The schematic netlist publishes duplicate or case-colliding .SUBCKT names.",
        )
    return tuple(declarations)


def _load_simra_bundle_validator() -> Callable[..., object] | None:
    """Load the release-pinned Simra validator when its source root is present.

    The production image exposes the same immutable Simra checkout used by the
    schematic compiler through ``OPENADA_SIMRA_VALIDATOR_ROOT`` or the existing
    ``SANDBOXY_SIMRA_VALIDATOR_ROOT`` compatibility name. Coordinated source
    workspaces and Simra virtual environments provide two additional explicit
    roots. Do not import an ambient ``plugins`` package from the caller's
    working directory: in standalone OpenADA installations, absence of one of
    these pinned roots deliberately selects the structural compatibility
    battery.
    """

    configured_values = [
        value
        for value in (
            os.environ.get("OPENADA_SIMRA_VALIDATOR_ROOT"),
            os.environ.get("SANDBOXY_SIMRA_VALIDATOR_ROOT"),
        )
        if value is not None
    ]
    if len(set(configured_values)) > 1:
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "OPENADA_SIMRA_VALIDATOR_ROOT and "
            "SANDBOXY_SIMRA_VALIDATOR_ROOT identify different checkouts.",
        )
    configured = configured_values[0] if configured_values else None
    candidates: list[tuple[Path, bool]] = []
    if configured is not None:
        configured_root = Path(configured).expanduser()
        if not configured_root.is_absolute():
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                "The configured Simra validator root must identify one "
                "absolute release-pinned checkout.",
            )
        candidates.append((configured_root, True))
    candidates.extend(
        (
            (Path("/opt/sim/simra/current"), False),
            (
                Path(__file__).resolve().parents[3].parent / "simra",
                False,
            ),
            (Path(sys.prefix).resolve().parent, False),
        )
    )

    seen: set[Path] = set()
    for candidate, required in candidates:
        try:
            root = candidate.resolve()
        except OSError as exc:
            if required:
                raise SimraArtifactError(
                    "experiment.dut.bundle_invalid",
                    "The configured release-pinned Simra validator root could "
                    "not be resolved.",
                ) from exc
            continue
        if root in seen:
            continue
        seen.add(root)
        module_file = root / "plugins/schematic/compiler/bundle.py"
        if not module_file.is_file():
            if required:
                raise SimraArtifactError(
                    "experiment.dut.bundle_invalid",
                    "The configured release-pinned Simra checkout does not "
                    "contain the schematic bundle validator.",
                )
            continue

        root_text = str(root)
        inserted = root_text not in sys.path
        if inserted:
            sys.path.insert(0, root_text)
        try:
            module = importlib.import_module(
                "plugins.schematic.compiler.bundle"
            )
        except Exception as exc:
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                "The release-pinned Simra schematic bundle validator could "
                "not be imported.",
            ) from exc
        finally:
            if inserted:
                try:
                    sys.path.remove(root_text)
                except ValueError:
                    pass

        loaded_path = Path(str(getattr(module, "__file__", "")))
        try:
            loaded_path.resolve().relative_to(root)
        except (OSError, ValueError) as exc:
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                "The Simra schematic bundle validator resolved outside the "
                "release-pinned source root.",
            ) from exc
        validator = getattr(module, "validate_bundle_bytes", None)
        if not callable(validator):
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                "The release-pinned Simra schematic bundle validator has an "
                "unsupported API.",
            )
        return validator
    return None


def _validate_with_simra_bundle_validator(
    validator: Callable[..., object],
    *,
    descriptor_bytes: bytes,
    source_bytes: bytes,
    view_bytes: bytes,
    netlist_bytes: bytes,
    cdl_bytes: bytes,
    expected_top: str,
) -> None:
    """Require Simra's full deterministic validation of the captured bytes."""

    files = {
        "schematic.artifact.json": descriptor_bytes,
        "design.ord": source_bytes,
        "schematic.simra.json": view_bytes,
        "design.spice": netlist_bytes,
        "design.cdl": cdl_bytes,
    }
    try:
        validated = validator(files, source_bytes, expected_top)
    except Exception as exc:
        detail = str(exc).replace("\r", " ").replace("\n", " ").strip()
        if len(detail) > 1_000:
            detail = detail[:997] + "..."
        suffix = f": {detail}" if detail else f" ({type(exc).__name__})"
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The release-pinned Simra validator rejected the captured "
            f"five-file schematic bundle{suffix}",
        ) from exc
    if not isinstance(validated, Mapping):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The release-pinned Simra validator returned an unsupported result.",
        )


@dataclass(frozen=True, slots=True)
class _StructuralCard:
    kind: str
    tokens: tuple[str, ...]
    node_count: int


def _netlist_view_mismatch(message: str) -> NoReturn:
    raise SimraArtifactError(
        "experiment.dut.netlist_view_mismatch",
        "The captured design.spice does not structurally match "
        f"schematic.simra.json: {message}",
    )


def _structural_token(value: object, *, label: str) -> str:
    if isinstance(value, bool) or value is None:
        _netlist_view_mismatch(f"{label} is not one SPICE token")
    if isinstance(value, float) and not math.isfinite(value):
        _netlist_view_mismatch(f"{label} is not finite")
    if not isinstance(value, (str, int, float)):
        _netlist_view_mismatch(f"{label} is not one SPICE scalar")
    token = str(value)
    if _SAFE_SPICE_TOKEN_RE.fullmatch(token) is None:
        _netlist_view_mismatch(f"{label} is not one bounded SPICE token")
    return token


def _prefixed_instance_name(name: str, kind: str) -> str:
    prefix = _DEVICE_SPICE_PREFIX.get(kind)
    if prefix is None:
        _netlist_view_mismatch(
            f"view instance {name!r} has unsupported kind {kind!r}"
        )
    return name if name[:1].upper() == prefix else f"{prefix}_{name}"


def _primitive_parameter_tokens(
    instance: Mapping[str, Any],
    *,
    name: str,
    kind: str,
) -> tuple[str, ...]:
    parameters = instance.get("parameters")
    if not isinstance(parameters, Mapping):
        _netlist_view_mismatch(
            f"view instance {name!r} has no parameters object"
        )
    allowed = _STRUCTURAL_PARAMETER_KEYS.get(kind)
    if allowed is None:
        _netlist_view_mismatch(
            f"view instance {name!r} has unsupported DUT kind {kind!r}"
        )
    if not all(isinstance(key, str) for key in parameters):
        _netlist_view_mismatch(
            f"view instance {name!r} has a non-string parameter name"
        )
    unexpected = set(parameters) - allowed
    if unexpected:
        _netlist_view_mismatch(
            f"view instance {name!r} has unsupported parameter(s) "
            + ", ".join(sorted(str(key) for key in unexpected))
        )

    def value(key: str) -> str:
        if key not in parameters:
            _netlist_view_mismatch(
                f"view instance {name!r} is missing parameter {key!r}"
            )
        return _structural_token(
            parameters[key],
            label=f"view instance {name!r} parameter {key!r}",
        )

    if kind in {"nmos", "pmos"}:
        return (
            value("model"),
            f"W={value('w')}",
            f"L={value('l')}",
            f"M={value('m')}",
            f"NF={value('nf')}",
        )
    if kind == "resistor":
        return (value("r"),)
    if kind == "capacitor":
        tokens = [value("c")]
        if "ic" in parameters:
            tokens.append(f"IC={value('ic')}")
        return tuple(tokens)
    if kind == "inductor":
        return (value("l"),)
    if kind in {"vcvs", "vccs"}:
        return (value("gain"),)
    _netlist_view_mismatch(
        f"view instance {name!r} has unsupported DUT kind {kind!r}"
    )


def _expected_structural_netlist(
    view_document: Mapping[str, Any],
) -> dict[str, tuple[tuple[str, ...], dict[str, _StructuralCard]]]:
    raw_cells = view_document.get("cells")
    if not isinstance(raw_cells, list):
        _netlist_view_mismatch("the view contains no cells array")
    all_cells = [cell for cell in raw_cells if isinstance(cell, Mapping)]
    if len(all_cells) != len(raw_cells):
        _netlist_view_mismatch("the view contains a non-object cell")
    cell_by_id: dict[str, Mapping[str, Any]] = {}
    for cell in all_cells:
        cell_id = cell.get("id")
        if not isinstance(cell_id, str) or cell_id in cell_by_id:
            _netlist_view_mismatch(
                "the view contains a missing or duplicate cell id"
            )
        cell_by_id[cell_id] = cell

    expected: dict[
        str, tuple[tuple[str, ...], dict[str, _StructuralCard]]
    ] = {}
    folded_cells: set[str] = set()
    for cell in all_cells:
        if cell.get("kind") != "design":
            continue
        cell_name = cell.get("name")
        if (
            not isinstance(cell_name, str)
            or _SAFE_SPICE_TOKEN_RE.fullmatch(cell_name) is None
        ):
            _netlist_view_mismatch("a design cell has no SPICE-safe name")
        folded_cell = cell_name.casefold()
        if folded_cell in folded_cells:
            _netlist_view_mismatch(
                f"design cell name {cell_name!r} collides case-insensitively"
            )
        folded_cells.add(folded_cell)

        entities = cell.get("entities")
        if not isinstance(entities, Mapping):
            _netlist_view_mismatch(
                f"design cell {cell_name!r} has no entities object"
            )
        raw_nets = entities.get("nets")
        if not isinstance(raw_nets, list):
            _netlist_view_mismatch(
                f"design cell {cell_name!r} has no nets array"
            )
        net_by_id: dict[str, str] = {}
        folded_nets: set[str] = set()
        for net in raw_nets:
            if not isinstance(net, Mapping):
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains a non-object net"
                )
            net_id = net.get("id")
            net_name = net.get("name")
            if (
                not isinstance(net_id, str)
                or net_id in net_by_id
                or not isinstance(net_name, str)
                or _SAFE_SPICE_TOKEN_RE.fullmatch(net_name) is None
            ):
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains an invalid net"
                )
            if net_name == "0":
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} names an internal net literal 0"
                )
            folded_net = net_name.casefold()
            if folded_net in folded_nets:
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains colliding net names"
                )
            folded_nets.add(folded_net)
            net_by_id[net_id] = net_name

        raw_ports = entities.get("ports")
        raw_port_order = cell.get("port_order")
        if not isinstance(raw_ports, list) or not isinstance(
            raw_port_order, list
        ):
            _netlist_view_mismatch(
                f"design cell {cell_name!r} has no complete port map"
            )
        port_by_name: dict[str, Mapping[str, Any]] = {}
        for port in raw_ports:
            if not isinstance(port, Mapping):
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains a non-object port"
                )
            port_name = port.get("name")
            if not isinstance(port_name, str) or port_name in port_by_name:
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains an invalid port"
                )
            port_by_name[port_name] = port
        if (
            not all(isinstance(name, str) for name in raw_port_order)
            or len(port_by_name) != len(raw_port_order)
            or set(port_by_name) != set(raw_port_order)
        ):
            _netlist_view_mismatch(
                f"design cell {cell_name!r} port_order disagrees with its ports"
            )
        port_nets: list[str] = []
        for port_name in raw_port_order:
            net_id = port_by_name[port_name].get("net")
            if not isinstance(net_id, str) or net_id not in net_by_id:
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} port {port_name!r} "
                    "does not resolve through the net map"
                )
            port_nets.append(net_by_id[net_id])

        raw_instances = entities.get("instances")
        if not isinstance(raw_instances, list):
            _netlist_view_mismatch(
                f"design cell {cell_name!r} has no instances array"
            )
        cards: dict[str, _StructuralCard] = {}
        for instance in raw_instances:
            if not isinstance(instance, Mapping):
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains a non-object instance"
                )
            name = instance.get("name")
            kind = instance.get("kind")
            terminals = instance.get("terminals")
            if (
                not isinstance(name, str)
                or _SAFE_SPICE_TOKEN_RE.fullmatch(name) is None
                or not isinstance(kind, str)
                or not isinstance(terminals, Mapping)
            ):
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains an invalid instance"
                )
            spice_name = _prefixed_instance_name(name, kind)
            folded_name = spice_name.casefold()
            if folded_name in cards:
                _netlist_view_mismatch(
                    f"design cell {cell_name!r} contains colliding emitted "
                    f"instance name {spice_name!r}"
                )

            if kind == "cell":
                target_id = instance.get("cell_ref")
                target = (
                    cell_by_id.get(target_id)
                    if isinstance(target_id, str)
                    else None
                )
                if not isinstance(target, Mapping) or target.get("kind") != "design":
                    _netlist_view_mismatch(
                        f"hierarchical instance {name!r} does not resolve to "
                        "one design cell"
                    )
                terminal_order = target.get("port_order")
                target_name = target.get("name")
                parameters = instance.get("parameters")
                if (
                    not isinstance(terminal_order, list)
                    or not all(
                        isinstance(terminal, str)
                        for terminal in terminal_order
                    )
                    or not isinstance(target_name, str)
                    or not isinstance(parameters, Mapping)
                    or parameters
                ):
                    _netlist_view_mismatch(
                        f"hierarchical instance {name!r} has invalid view metadata"
                    )
                tail = (target_name,)
            else:
                terminal_order = _DEVICE_TERMINALS.get(kind)
                if terminal_order is None:
                    _netlist_view_mismatch(
                        f"view instance {name!r} has unsupported kind {kind!r}"
                    )
                tail = _primitive_parameter_tokens(
                    instance,
                    name=name,
                    kind=kind,
                )

            nodes: list[str] = []
            if set(terminals) != set(terminal_order):
                _netlist_view_mismatch(
                    f"view instance {name!r} terminals disagree with kind "
                    f"{kind!r}"
                )
            for terminal in terminal_order:
                net_id = terminals.get(terminal)
                if not isinstance(net_id, str) or net_id not in net_by_id:
                    _netlist_view_mismatch(
                        f"view instance {name!r} terminal {terminal!r} does "
                        "not resolve through the cell net map"
                    )
                nodes.append(net_by_id[net_id])
            cards[folded_name] = _StructuralCard(
                kind=kind,
                tokens=(spice_name, *nodes, *tail),
                node_count=len(nodes),
            )
        expected[cell_name] = (tuple(port_nets), cards)
    return expected


def _actual_structural_netlist(
    netlist_text: str,
) -> dict[str, tuple[tuple[str, ...], list[tuple[str, ...]]]]:
    actual: dict[str, tuple[tuple[str, ...], list[tuple[str, ...]]]] = {}
    folded_cells: set[str] = set()
    active_name: str | None = None
    active_cards: list[tuple[str, ...]] | None = None
    for line_number, line in enumerate(netlist_text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("*"):
            continue
        tokens = tuple(stripped.split())
        directive = tokens[0].casefold()
        if directive == ".subckt":
            if active_name is not None or len(tokens) < 2:
                _netlist_view_mismatch(
                    f"line {line_number} contains an invalid or nested .SUBCKT"
                )
            active_name = tokens[1]
            folded_name = active_name.casefold()
            if folded_name in folded_cells:
                _netlist_view_mismatch(
                    f"line {line_number} repeats or case-collides a .SUBCKT"
                )
            folded_cells.add(folded_name)
            active_cards = []
            actual[active_name] = (tokens[2:], active_cards)
            continue
        if directive == ".ends":
            if (
                active_name is None
                or len(tokens) > 2
                or (len(tokens) == 2 and tokens[1] != active_name)
            ):
                _netlist_view_mismatch(
                    f"line {line_number} contains an unmatched .ENDS"
                )
            active_name = None
            active_cards = None
            continue
        if active_name is None or active_cards is None:
            _netlist_view_mismatch(
                f"line {line_number} contains content outside a DUT subcircuit"
            )
        if stripped.startswith("+") or stripped.startswith("."):
            _netlist_view_mismatch(
                f"line {line_number} contains a forbidden directive or continuation"
            )
        if not tokens[0] or _SAFE_SPICE_TOKEN_RE.fullmatch(tokens[0]) is None:
            _netlist_view_mismatch(
                f"line {line_number} contains an invalid device name"
            )
        if tokens[0][0].upper() in {"V", "I"}:
            raise SimraArtifactError(
                "experiment.dut.embedded_stimulus",
                "The captured design.spice contains an independent-source "
                f"card inside DUT subcircuit {active_name!r} at line "
                f"{line_number}.",
            )
        active_cards.append(tokens)
    if active_name is not None:
        _netlist_view_mismatch(
            f"DUT subcircuit {active_name!r} has no matching .ENDS"
        )
    if not actual:
        _netlist_view_mismatch("the netlist contains no DUT subcircuit")
    return actual


def _validate_structural_netlist_fallback(
    view_document: Mapping[str, Any],
    netlist_text: str,
) -> None:
    """Replay the view/netlist device relationship without importing Simra."""

    expected = _expected_structural_netlist(view_document)
    actual = _actual_structural_netlist(netlist_text)
    if set(actual) != set(expected):
        _netlist_view_mismatch(
            "the netlist and view publish different design-cell names"
        )
    for cell_name, (expected_ports, expected_cards) in expected.items():
        actual_ports, raw_cards = actual[cell_name]
        if actual_ports != expected_ports:
            _netlist_view_mismatch(
                f"subcircuit {cell_name!r} terminal incidence disagrees "
                "with the view port/net maps"
            )
        seen: set[str] = set()
        for tokens in raw_cards:
            folded_name = tokens[0].casefold()
            card = expected_cards.get(folded_name)
            if card is None or folded_name in seen:
                _netlist_view_mismatch(
                    f"subcircuit {cell_name!r} contains an extra, missing, "
                    f"or duplicate device card {tokens[0]!r}"
                )
            seen.add(folded_name)
            if len(tokens) < 1 + card.node_count:
                _netlist_view_mismatch(
                    f"device card {tokens[0]!r} has an incomplete node list"
                )
            if "0" in tokens[1 : 1 + card.node_count]:
                _netlist_view_mismatch(
                    f"device card {tokens[0]!r} connects to literal node 0"
                )
            if tokens != card.tokens:
                _netlist_view_mismatch(
                    f"device card {tokens[0]!r} disagrees in emitted name, "
                    f"kind, parameters, or net incidence"
                )
        if seen != set(expected_cards):
            missing = sorted(set(expected_cards) - seen)
            _netlist_view_mismatch(
                f"subcircuit {cell_name!r} omits view device card(s): "
                + ", ".join(missing)
            )


def load_simra_schematic_bundle(
    descriptor_file: str | Path,
    *,
    expected_digests: Mapping[str, str],
    expected_top: str,
) -> SimraSchematicBundle:
    """Capture and validate one promoted, schematic-only Simra DUT bundle.

    All five files are read exactly once into this immutable snapshot. The
    caller-supplied digest set identifies the publication to run; the
    descriptor's four member digests independently bind its own contents.
    Composition must use the returned bytes/text rather than reopen a member.
    """

    expected = _validated_expected_digests(expected_digests)
    if (
        not isinstance(expected_top, str)
        or not expected_top
        or len(expected_top) > 256
        or _SAFE_SPICE_TOKEN_RE.fullmatch(expected_top) is None
    ):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "dut.top must be one bounded SPICE-safe cell name.",
        )

    descriptor_path = Path(descriptor_file).expanduser()
    if not descriptor_path.is_absolute():
        raise SimraArtifactError(
            "experiment.dut.publication_untrusted",
            f"The schematic artifact descriptor locator must be absolute: {descriptor_path}",
        )
    directory = descriptor_path.parent
    descriptor_bytes, descriptor_sha256, descriptor_record = (
        _snapshot_regular_file(
            descriptor_path,
            kind="simra-artifact",
            role="artifact-descriptor",
            maximum_bytes=MAX_DESCRIPTOR_BYTES,
        )
    )
    descriptor_text = _utf8_text(
        descriptor_bytes,
        role="artifact descriptor",
        path=descriptor_path,
    )
    descriptor_document = _json_object(
        descriptor_text,
        role="artifact descriptor",
        path=descriptor_path,
    )

    if descriptor_document.get("schema") != ARTIFACT_SCHEMA:
        raise SimraArtifactError(
            "experiment.dut.kind_unsupported",
            f"Expected a {ARTIFACT_SCHEMA} descriptor, got "
            f"{descriptor_document.get('schema')!r}.",
        )
    if descriptor_document.get("kind") != "schematic":
        raise SimraArtifactError(
            "experiment.dut.kind_unsupported",
            f"The published artifact kind is {descriptor_document.get('kind')!r}; "
            "the experiment DUT must be schematic-only.",
        )

    source_path = _schematic_member_path(
        directory,
        descriptor_document.get("source"),
        field_name="source",
    )
    view_path = _schematic_member_path(
        directory,
        descriptor_document.get("view"),
        field_name="view",
    )
    netlist_path = _schematic_member_path(
        directory,
        descriptor_document.get("netlist"),
        field_name="netlist",
    )
    cdl_path = _schematic_member_path(
        directory,
        descriptor_document.get("cdl"),
        field_name="cdl",
    )
    member_paths = (source_path, view_path, netlist_path, cdl_path)
    published_paths = (descriptor_path, *member_paths)
    if len({path.name.casefold() for path in published_paths}) != len(
        published_paths
    ):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The bundle must contain five distinct descriptor, source, view, "
            "netlist, and CDL files.",
        )

    source_bytes, source_sha256, source_record = _snapshot_regular_file(
        source_path,
        kind="simra-source",
        role="schematic-source",
        maximum_bytes=MAX_SOURCE_BYTES,
    )
    view_bytes, view_sha256, view_record = _snapshot_regular_file(
        view_path,
        kind="simra-artifact",
        role="schematic-view",
        maximum_bytes=MAX_VIEW_BYTES,
    )
    netlist_bytes, netlist_sha256, netlist_record = _snapshot_regular_file(
        netlist_path,
        kind="spice-netlist",
        role="netlist",
        maximum_bytes=MAX_DECK_BYTES,
    )
    cdl_bytes, cdl_sha256, cdl_record = _snapshot_regular_file(
        cdl_path,
        kind="cdl-netlist",
        role="cdl",
        maximum_bytes=MAX_CDL_BYTES,
    )

    source_text = _utf8_text(
        source_bytes,
        role="source",
        path=source_path,
    )
    view_text = _utf8_text(
        view_bytes,
        role="view",
        path=view_path,
    )
    netlist_text = _utf8_text(
        netlist_bytes,
        role="netlist",
        path=netlist_path,
    )
    cdl_text = _utf8_text(
        cdl_bytes,
        role="CDL",
        path=cdl_path,
    )
    view_document = _json_object(
        view_text,
        role="view",
        path=view_path,
    )

    actual_digests = {
        "descriptor_sha256": descriptor_sha256,
        "source_sha256": source_sha256,
        "view_sha256": view_sha256,
        "netlist_sha256": netlist_sha256,
        "cdl_sha256": cdl_sha256,
    }
    caller_mismatches = [
        name
        for name in _SCHEMATIC_DIGEST_KEYS
        if expected[name] != actual_digests[name]
    ]
    if caller_mismatches:
        details = ", ".join(
            f"{name}: expected {expected[name]}, captured {actual_digests[name]}"
            for name in caller_mismatches
        )
        raise SimraArtifactError(
            "experiment.dut.digest_mismatch",
            f"The captured schematic bundle disagrees with dut.bundle ({details}).",
        )

    hashes = descriptor_document.get("hashes")
    if not isinstance(hashes, Mapping):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The schematic descriptor publishes no hashes object.",
        )
    published_mismatches: list[str] = []
    for name in ("source_sha256", "view_sha256", "netlist_sha256", "cdl_sha256"):
        published = hashes.get(name)
        if not isinstance(published, str) or _SHA256_RE.fullmatch(published) is None:
            raise SimraArtifactError(
                "experiment.dut.bundle_invalid",
                f"The schematic descriptor publishes no valid hashes.{name}.",
            )
        if published != actual_digests[name]:
            published_mismatches.append(name)
    if published_mismatches:
        details = ", ".join(
            f"{name}: published {hashes[name]}, captured {actual_digests[name]}"
            for name in published_mismatches
        )
        raise SimraArtifactError(
            "experiment.dut.digest_mismatch",
            f"The descriptor's member digests are stale ({details}).",
        )

    if view_document.get("schema") != VIEW_SCHEMA:
        raise SimraArtifactError(
            "experiment.dut.kind_unsupported",
            f"Expected a {VIEW_SCHEMA} view, got {view_document.get('schema')!r}.",
        )
    view = view_document.get("view")
    if not isinstance(view, Mapping) or view.get("kind") != "schematic":
        raise SimraArtifactError(
            "experiment.dut.kind_unsupported",
            "The published view is not a schematic-only view.",
        )
    if view_document.get("testbench") is not None:
        raise SimraArtifactError(
            "experiment.dut.embedded_testbench",
            "The schematic DUT embeds a testbench declaration.",
        )

    identifier = descriptor_document.get("id")
    if (
        not isinstance(identifier, str)
        or not identifier
        or len(identifier) > 256
        or view.get("id") != identifier
    ):
        raise SimraArtifactError(
            "experiment.dut.bundle_invalid",
            "The descriptor and view do not publish one consistent bounded artifact id.",
        )
    label = descriptor_document.get("label")
    if not isinstance(label, str) or len(label) > 512:
        label = identifier

    descriptor_top = descriptor_document.get("top")
    view_top = view.get("top")
    if descriptor_top != expected_top or view_top != expected_top:
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            f"dut.top={expected_top!r}, descriptor.top={descriptor_top!r}, and "
            f"view.top={view_top!r} do not identify the same cell.",
        )

    design_cells, view_design_names = _design_cells(view_document)
    all_cells = view_document["cells"]
    if any(
        isinstance(cell, Mapping) and cell.get("kind") == "testbench"
        for cell in all_cells
    ):
        raise SimraArtifactError(
            "experiment.dut.embedded_testbench",
            "The schematic DUT embeds a testbench cell.",
        )
    top_cell_id = view.get("top_cell")
    top_cells = [
        cell
        for cell in design_cells
        if cell.get("name") == expected_top and cell.get("id") == top_cell_id
    ]
    if len(top_cells) != 1:
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The view's top/top_cell pair does not identify exactly one design cell.",
        )
    top_cell = top_cells[0]

    raw_port_order = top_cell.get("port_order")
    if not isinstance(raw_port_order, list) or not all(
        isinstance(name, str)
        and len(name) <= 256
        and _SAFE_SPICE_TOKEN_RE.fullmatch(name) is not None
        for name in raw_port_order
    ):
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The top design cell publishes no bounded SPICE-safe port_order.",
        )
    port_order = tuple(raw_port_order)
    if len({name.casefold() for name in port_order}) != len(port_order):
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The top design cell's port_order contains duplicate or case-colliding ports.",
        )
    if any(name == "0" for name in port_order):
        raise SimraArtifactError(
            "experiment.dut.global_ground_internal",
            "The DUT must expose ground through an ordinary port bound externally; "
            "a DUT port may not be named literal 0.",
        )

    top_entities = top_cell.get("entities")
    top_ports = (
        top_entities.get("ports") if isinstance(top_entities, Mapping) else None
    )
    if not isinstance(top_ports, list) or not all(
        isinstance(port, Mapping)
        and isinstance(port.get("name"), str)
        and isinstance(port.get("ordinal"), int)
        and not isinstance(port.get("ordinal"), bool)
        for port in top_ports
    ):
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The top design cell publishes no typed port entities.",
        )
    ordered_ports = sorted(top_ports, key=lambda port: port["ordinal"])
    if (
        [port["ordinal"] for port in ordered_ports] != list(range(len(port_order)))
        or tuple(port["name"] for port in ordered_ports) != port_order
    ):
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The top design cell's port entities disagree with port_order.",
        )

    declarations = _netlist_subckts(netlist_text)
    netlist_design_names = tuple(name for name, _ports in declarations)
    if (
        {name.casefold(): name for name in netlist_design_names}
        != {name.casefold(): name for name in view_design_names}
    ):
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The netlist .SUBCKT names disagree with the view's design cells.",
        )
    top_declarations = [
        ports for name, ports in declarations if name == expected_top
    ]
    if len(top_declarations) != 1 or top_declarations[0] != port_order:
        raise SimraArtifactError(
            "experiment.dut.port_abi_mismatch",
            "The top .SUBCKT terminal order disagrees with the view's port_order.",
        )

    embedded_sources: list[str] = []
    embedded_grounds: list[str] = []
    internal_ground_nets: list[str] = []
    for cell in all_cells:
        if not isinstance(cell, Mapping):
            continue
        entities = cell.get("entities")
        if not isinstance(entities, Mapping):
            continue
        instances = entities.get("instances")
        if isinstance(instances, list):
            for instance in instances:
                if not isinstance(instance, Mapping):
                    continue
                kind = instance.get("kind")
                name = str(instance.get("name") or instance.get("id") or "?")
                if kind in _INDEPENDENT_SOURCE_KINDS:
                    embedded_sources.append(name)
                if kind == "ground":
                    embedded_grounds.append(name)
                terminals = instance.get("terminals")
                if isinstance(terminals, Mapping) and any(
                    value == "0" for value in terminals.values()
                ):
                    internal_ground_nets.append(name)
        nets = entities.get("nets")
        if isinstance(nets, list):
            for net in nets:
                if isinstance(net, Mapping) and net.get("name") == "0":
                    internal_ground_nets.append(
                        str(net.get("id") or f"{cell.get('name')}:0")
                    )

    if embedded_sources:
        raise SimraArtifactError(
            "experiment.dut.embedded_stimulus",
            "The schematic DUT contains independent-source instance(s): "
            + ", ".join(embedded_sources),
        )
    if embedded_grounds or internal_ground_nets:
        details = embedded_grounds + internal_ground_nets
        raise SimraArtifactError(
            "experiment.dut.global_ground_internal",
            "The schematic DUT contains an internal ground instance or literal-0 "
            "net reference: "
            + ", ".join(details),
        )

    lifecycle = _rederive_lifecycle_v2(view_document, netlist_text)
    if lifecycle["state"] != "simulation_candidate":
        raise SimraArtifactError(
            "experiment.dut.not_promoted",
            "The exact bundle bytes rederive as display_candidate: "
            + json.dumps(
                {
                    "unresolved": lifecycle["unresolved"],
                    "blockers": lifecycle["blockers"],
                },
                sort_keys=True,
                separators=(",", ":"),
            ),
        )

    validator = _load_simra_bundle_validator()
    if validator is not None:
        _validate_with_simra_bundle_validator(
            validator,
            descriptor_bytes=descriptor_bytes,
            source_bytes=source_bytes,
            view_bytes=view_bytes,
            netlist_bytes=netlist_bytes,
            cdl_bytes=cdl_bytes,
            expected_top=expected_top,
        )
    # Keep the structural replay even when the full validator is present. It
    # independently enforces the experiment-specific prohibition on literal
    # node 0 and independent sources inside reusable DUT subcircuits.
    _validate_structural_netlist_fallback(view_document, netlist_text)

    records = (
        descriptor_record,
        source_record,
        view_record,
        netlist_record,
        cdl_record,
    )
    return SimraSchematicBundle(
        descriptor_path=Path(descriptor_record["path"]),
        source_path=Path(source_record["path"]),
        view_path=Path(view_record["path"]),
        netlist_path=Path(netlist_record["path"]),
        cdl_path=Path(cdl_record["path"]),
        directory=directory,
        identifier=identifier,
        label=label,
        top=expected_top,
        port_order=port_order,
        design_subckt_names=netlist_design_names,
        lifecycle=lifecycle,
        descriptor_document=descriptor_document,
        view_document=view_document,
        descriptor_bytes=descriptor_bytes,
        source_bytes=source_bytes,
        view_bytes=view_bytes,
        netlist_bytes=netlist_bytes,
        cdl_bytes=cdl_bytes,
        descriptor_text=descriptor_text,
        source_text=source_text,
        view_text=view_text,
        netlist_text=netlist_text,
        cdl_text=cdl_text,
        descriptor_sha256=descriptor_sha256,
        source_sha256=source_sha256,
        view_sha256=view_sha256,
        netlist_sha256=netlist_sha256,
        cdl_sha256=cdl_sha256,
        descriptor_record=descriptor_record,
        source_record=source_record,
        view_record=view_record,
        netlist_record=netlist_record,
        cdl_record=cdl_record,
        input_records=records,
    )


def _read_json_document(
    path: Path,
    *,
    role: str,
    maximum_bytes: int,
) -> tuple[dict[str, Any], str, dict[str, Any]]:
    """Return one bounded JSON object with its digest and retained file record."""

    try:
        record = file_record(
            path,
            kind="simra-artifact",
            role=role,
            maximum_bytes=maximum_bytes,
        )
    except FileRecordLimitError as exc:
        raise SimraArtifactError(
            "testbench.artifact.over_limit",
            f"The Simra {role} exceeds the bounded {maximum_bytes}-byte limit: {exc.observed_bytes} bytes.",
        ) from exc
    except FileRecordError as exc:
        raise SimraArtifactError(
            "testbench.artifact.unstable",
            f"The Simra {role} could not be captured as one stable regular file: {path}",
        ) from exc
    if not record["exists"]:
        raise SimraArtifactError(
            "testbench.artifact.missing",
            f"The Simra {role} is not a readable regular file: {path}",
        )

    try:
        with stable_regular_file(path) as (handle, _opened):
            raw = handle.read(maximum_bytes + 1)
    except FileRecordError as exc:
        raise SimraArtifactError(
            "testbench.artifact.unstable",
            f"The Simra {role} changed during bounded capture: {path}",
        ) from exc
    if len(raw) > maximum_bytes:
        raise SimraArtifactError(
            "testbench.artifact.over_limit",
            f"The Simra {role} exceeds the bounded {maximum_bytes}-byte limit.",
        )
    if hashlib.sha256(raw).hexdigest() != record["sha256"]:
        raise SimraArtifactError(
            "testbench.artifact.unstable",
            f"The Simra {role} changed between digest capture and read: {path}",
        )
    try:
        document = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            f"The Simra {role} is not one valid UTF-8 JSON document: {path}",
        ) from exc
    if not isinstance(document, dict):
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            f"The Simra {role} is not a JSON object: {path}",
        )
    return document, record["sha256"], record


def _read_text_file(
    path: Path,
    *,
    kind: str,
    role: str,
    maximum_bytes: int,
) -> tuple[str, str, dict[str, Any]]:
    try:
        record = file_record(path, kind=kind, role=role, maximum_bytes=maximum_bytes)
    except FileRecordLimitError as exc:
        raise SimraArtifactError(
            "testbench.artifact.over_limit",
            f"The Simra {role} exceeds the bounded {maximum_bytes}-byte limit: {exc.observed_bytes} bytes.",
        ) from exc
    except FileRecordError as exc:
        raise SimraArtifactError(
            "testbench.artifact.unstable",
            f"The Simra {role} could not be captured as one stable regular file: {path}",
        ) from exc
    if not record["exists"]:
        raise SimraArtifactError(
            "testbench.artifact.missing",
            f"The Simra {role} is not a readable regular file: {path}",
        )
    try:
        with stable_regular_file(path) as (handle, _opened):
            raw = handle.read(maximum_bytes + 1)
    except FileRecordError as exc:
        raise SimraArtifactError(
            "testbench.artifact.unstable",
            f"The Simra {role} changed during bounded capture: {path}",
        ) from exc
    if len(raw) > maximum_bytes:
        raise SimraArtifactError(
            "testbench.artifact.over_limit",
            f"The Simra {role} exceeds the bounded {maximum_bytes}-byte limit.",
        )
    if hashlib.sha256(raw).hexdigest() != record["sha256"]:
        raise SimraArtifactError(
            "testbench.artifact.unstable",
            f"The Simra {role} changed between digest capture and read: {path}",
        )
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            f"The Simra {role} is not valid UTF-8: {path}",
        ) from exc
    return text, record["sha256"], record


def _sibling(directory: Path, value: object, *, field_name: str) -> Path:
    if not isinstance(value, str) or _PATH_COMPONENT_RE.fullmatch(value) is None:
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            f"The descriptor {field_name!r} must be one bounded published file name in the artifact directory.",
        )
    candidate = directory / value
    if candidate.parent != directory:
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            f"The descriptor {field_name!r} must not escape the artifact directory.",
        )
    return candidate


def _diagnostic_name(value: object) -> str:
    if isinstance(value, str) and _DIAGNOSTIC_NAME_RE.fullmatch(value) is not None:
        return bounded_text(value, limit=MAX_DIAGNOSTIC_NAME_CHARS)
    return "unknown"


def _diagnostic_kind(value: object) -> str:
    if isinstance(value, str) and _DIAGNOSTIC_KIND_RE.fullmatch(value) is not None:
        return value
    return "unknown"


def _artifact_local_location(
    source: object,
    *,
    descriptor_source: object,
) -> str:
    """Return a bounded source locator that cannot disclose a host path."""

    published_name = (
        descriptor_source
        if isinstance(descriptor_source, str)
        and _PATH_COMPONENT_RE.fullmatch(descriptor_source) is not None
        else None
    )
    line: int | None = None
    column: int | None = None
    if isinstance(source, Mapping):
        source_name = source.get("artifact")
        if (
            isinstance(source_name, str)
            and _PATH_COMPONENT_RE.fullmatch(source_name) is not None
        ):
            published_name = source_name
        candidate_line = source.get("line")
        if (
            isinstance(candidate_line, int)
            and not isinstance(candidate_line, bool)
            and 1 <= candidate_line <= 1_000_000_000
        ):
            line = candidate_line
        candidate_column = source.get("column")
        if (
            isinstance(candidate_column, int)
            and not isinstance(candidate_column, bool)
            and 0 <= candidate_column <= 1_000_000_000
        ):
            column = candidate_column

    location = (
        f"artifact-local {published_name}"
        if published_name is not None
        else "the artifact-local source"
    )
    if line is not None:
        location += f":{line}"
        if column is not None:
            location += f":{column}"
    return location


def _instance_placeholder_prefix(name: str) -> str:
    token = re.sub(r"[^A-Za-z0-9_]", "_", name).upper()
    return f"SIMRA_UNRESOLVED_{token}_"


def _unresolved_placeholders(
    deck_text: str,
    *,
    top_cell: str,
) -> list[_UnresolvedPlaceholder]:
    """Return each distinct placeholder with its netlist cell context."""

    cell_stack: list[str] = []
    seen: set[tuple[str | None, str]] = set()
    unresolved: list[_UnresolvedPlaceholder] = []
    for line in deck_text.splitlines():
        subcircuit = _SUBCKT_CELL_RE.match(line)
        if subcircuit is not None:
            cell_stack.append(subcircuit.group("cell"))
        cell_name = cell_stack[-1] if cell_stack else top_cell
        for token in dict.fromkeys(UNRESOLVED_TOKEN_RE.findall(line)):
            key = (cell_name.casefold(), token)
            if key not in seen:
                seen.add(key)
                unresolved.append(
                    _UnresolvedPlaceholder(token=token, cell_name=cell_name)
                )
        if _ENDS_RE.match(line) is not None and cell_stack:
            cell_stack.pop()
    return unresolved


def _unresolved_parameter_diagnostic(
    *,
    parameters_state: object,
    unresolved: list[_UnresolvedPlaceholder],
    view_document: Mapping[str, Any],
    descriptor_source: object,
) -> tuple[str, str]:
    """Describe unresolved authoring values using only bounded artifact-local facts."""

    examples = unresolved[:MAX_UNRESOLVED_EXAMPLES]
    best_matches: dict[
        int,
        tuple[tuple[int, int], list[dict[str, str]]],
    ] = {}
    nonresolved_instances: list[dict[str, str]] = []

    cells = view_document.get("cells")
    if isinstance(cells, list):
        for cell in cells:
            if not isinstance(cell, Mapping):
                continue
            raw_cell_name = cell.get("name")
            cell_name = _diagnostic_name(raw_cell_name)
            raw_cell_kind = cell.get("kind")
            if raw_cell_kind == "design":
                cell_role = "circuit"
            elif raw_cell_kind == "testbench":
                cell_role = "testbench"
            else:
                cell_role = "published"
            entities = cell.get("entities")
            if not isinstance(entities, Mapping):
                continue
            instances = entities.get("instances")
            if not isinstance(instances, list):
                continue
            for instance in instances:
                if not isinstance(instance, Mapping):
                    continue
                raw_name = instance.get("name")
                if (
                    not isinstance(raw_name, str)
                    or _DIAGNOSTIC_NAME_RE.fullmatch(raw_name) is None
                ):
                    continue
                record = {
                    "cell_name": cell_name,
                    "cell_role": cell_role,
                    "device_kind": _diagnostic_kind(instance.get("kind")),
                    "instance_name": _diagnostic_name(raw_name),
                    "location": _artifact_local_location(
                        instance.get("source"),
                        descriptor_source=descriptor_source,
                    ),
                }
                parameter_status = instance.get("parameter_status")
                is_nonresolved = (
                    parameter_status == "partial"
                    or parameter_status == "unresolved"
                )
                if (
                    is_nonresolved
                    and len(nonresolved_instances) < MAX_UNRESOLVED_EXAMPLES
                ):
                    nonresolved_instances.append(record)

                prefix = _instance_placeholder_prefix(raw_name)
                for occurrence_index, occurrence in enumerate(examples):
                    if (
                        occurrence.cell_name is not None
                        and (
                            not isinstance(raw_cell_name, str)
                            or raw_cell_name.casefold()
                            != occurrence.cell_name.casefold()
                        )
                    ):
                        continue
                    token = occurrence.token
                    if not token.startswith(prefix):
                        continue
                    parameter = token[len(prefix) :]
                    if _DIAGNOSTIC_PARAMETER_RE.fullmatch(parameter) is None:
                        continue
                    candidate = dict(record)
                    candidate["parameter"] = parameter.casefold()
                    # A full instance-name match wins over a shorter prefix
                    # (M_1 over M). Netlist cell context disambiguates equal
                    # instance names in separate subcircuits. The view's
                    # non-resolved status breaks any remaining equal-name tie
                    # while still allowing a deck-tamper refusal to map a token
                    # whose view status remains "resolved".
                    rank = (len(prefix), 1 if is_nonresolved else 0)
                    current = best_matches.get(occurrence_index)
                    if current is None or rank > current[0]:
                        best_matches[occurrence_index] = (rank, [candidate])
                    elif rank == current[0] and len(current[1]) < MAX_UNRESOLVED_EXAMPLES:
                        current[1].append(candidate)

    grouped: dict[tuple[str, str, str, str, str], list[str]] = {}
    mapped: set[int] = set()
    ambiguous: dict[int, list[dict[str, str]]] = {}
    for occurrence_index, _occurrence in enumerate(examples):
        match = best_matches.get(occurrence_index)
        if match is None:
            continue
        distinct = {
            (
                candidate["cell_role"],
                candidate["cell_name"],
                candidate["device_kind"],
                candidate["instance_name"],
                candidate["location"],
            ): candidate
            for candidate in match[1]
        }
        if len(distinct) != 1:
            ambiguous[occurrence_index] = list(distinct.values())
            continue
        candidate = next(iter(distinct.values()))
        key = (
            candidate["cell_role"],
            candidate["cell_name"],
            candidate["device_kind"],
            candidate["instance_name"],
            candidate["location"],
        )
        parameters = grouped.setdefault(key, [])
        parameter = candidate["parameter"]
        if parameter not in parameters:
            parameters.append(parameter)
        mapped.add(occurrence_index)

    if unresolved:
        details = [
            (
                f"{device_kind} instance {instance_name!r} in {cell_role} "
                f"cell {cell_name!r} at {location} has unset parameters: "
                + ", ".join(parameters)
            )
            for (
                cell_role,
                cell_name,
                device_kind,
                instance_name,
                location,
            ), parameters in grouped.items()
        ]
        message = (
            f"The published artifact carries {len(unresolved)} unresolved "
            "parameter placeholder(s)"
        )
        if details:
            message += ": " + "; ".join(details)
        if ambiguous:
            candidates = []
            for occurrence_index, records in ambiguous.items():
                locations = ", ".join(
                    (
                        f"{item['device_kind']} instance "
                        f"{item['instance_name']!r} in {item['cell_role']} cell "
                        f"{item['cell_name']!r} at {item['location']}"
                    )
                    for item in records
                )
                candidates.append(
                    f"{bounded_text(examples[occurrence_index].token, limit=MAX_UNRESOLVED_TOKEN_DISPLAY_CHARS)}: "
                    f"{locations}"
                )
            message += (
                "; placeholder(s) with ambiguous view ownership: "
                + "; ".join(candidates)
            )
        unmapped = [
            occurrence.token
            for occurrence_index, occurrence in enumerate(examples)
            if occurrence_index not in mapped and occurrence_index not in ambiguous
        ]
        if unmapped:
            message += (
                "; placeholder(s) without bounded instance metadata: "
                + ", ".join(
                    bounded_text(
                        token,
                        limit=MAX_UNRESOLVED_TOKEN_DISPLAY_CHARS,
                    )
                    for token in unmapped
                )
            )
        omitted = len(unresolved) - len(examples)
        if omitted:
            message += (
                f"; {omitted} additional placeholder(s) omitted by the "
                f"{MAX_UNRESOLVED_EXAMPLES}-placeholder detail limit"
            )
        message += "."
        hint = (
            "Set the listed parameters at the named artifact-local source "
            "locations and recompile; this driver will not invent authoring values."
        )
        return bounded_text(message, limit=MAX_UNRESOLVED_MESSAGE_CHARS), hint

    state = (
        repr(parameters_state)
        if isinstance(parameters_state, str)
        and parameters_state in {"partial", "unresolved"}
        else "'invalid'"
    )
    message = (
        f"The published artifact reports validation.parameters={state}, but its "
        "digest-bound deck carries no unresolved parameter placeholders"
    )
    if nonresolved_instances:
        details = [
            (
                f"{item['device_kind']} instance {item['instance_name']!r} in "
                f"{item['cell_role']} cell {item['cell_name']!r} at "
                f"{item['location']}"
            )
            for item in nonresolved_instances
        ]
        message += "; the view marks these instances non-resolved: " + "; ".join(
            details
        )
    else:
        message += " and the view identifies no non-resolved instance"
    message += "."
    hint = (
        "Recompile the named artifact-local source so the view and deck publish "
        "matching unresolved parameter names; this driver will not invent "
        "authoring values."
    )
    return bounded_text(message, limit=MAX_UNRESOLVED_MESSAGE_CHARS), hint


def _typed_analysis(entry: object, position: int) -> dict[str, Any]:
    if not isinstance(entry, Mapping):
        raise SimraArtifactError(
            "testbench.analyses.invalid",
            f"Declared analysis {position} is not a JSON object.",
        )
    kind = entry.get("kind")
    if kind not in SUPPORTED_ANALYSIS_KINDS:
        raise SimraArtifactError(
            "testbench.analyses.unsupported",
            f"Declared analysis {position} has kind {kind!r}; "
            f"only {', '.join(SUPPORTED_ANALYSIS_KINDS)} are dispatchable.",
        )
    normalized: dict[str, Any] = {}
    for name, value in entry.items():
        if not isinstance(name, str) or len(name) > 64:
            raise SimraArtifactError(
                "testbench.analyses.invalid",
                f"Declared analysis {position} has an unbounded field name.",
            )
        if isinstance(value, str):
            if len(value) > 128:
                raise SimraArtifactError(
                    "testbench.analyses.invalid",
                    f"Declared analysis {position} field {name!r} is unbounded.",
                )
            normalized[name] = value
        elif isinstance(value, bool) or value is None:
            raise SimraArtifactError(
                "testbench.analyses.invalid",
                f"Declared analysis {position} field {name!r} is not a SPICE-typed value.",
            )
        elif isinstance(value, (int, float)):
            normalized[name] = value
        else:
            raise SimraArtifactError(
                "testbench.analyses.invalid",
                f"Declared analysis {position} field {name!r} is not a SPICE-typed value.",
            )
    return normalized


def load_simra_testbench(descriptor_file: str | Path) -> SimraTestbench:
    """Return one digest-verified, dispatchable Simra testbench artifact.

    Raises :class:`SimraArtifactError` with a stable diagnostic code when the
    artifact is absent, unstable, unbound, not a testbench, or carries anything
    the bounded simulation profiles cannot honestly run.
    """

    descriptor_path = Path(descriptor_file).expanduser()
    if not descriptor_path.is_absolute():
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            f"The artifact descriptor locator must be an absolute path: {descriptor_path}",
        )
    directory = descriptor_path.parent
    descriptor, _descriptor_sha, descriptor_record = _read_json_document(
        descriptor_path,
        role="artifact-descriptor",
        maximum_bytes=MAX_DESCRIPTOR_BYTES,
    )

    if descriptor.get("schema") != ARTIFACT_SCHEMA:
        raise SimraArtifactError(
            "testbench.artifact.unsupported_schema",
            f"Expected a {ARTIFACT_SCHEMA} descriptor, got {descriptor.get('schema')!r}.",
        )
    if descriptor.get("kind") != "testbench":
        raise SimraArtifactError(
            "testbench.artifact.not_a_testbench",
            f"The published artifact kind is {descriptor.get('kind')!r}; "
            "only a testbench declares analyses to dispatch.",
        )

    hashes = descriptor.get("hashes")
    if not isinstance(hashes, Mapping):
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            "The descriptor publishes no hashes object.",
        )
    validation = descriptor.get("validation")
    if not isinstance(validation, Mapping):
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            "The descriptor publishes no validation object.",
        )

    identifier = descriptor.get("id")
    top = descriptor.get("top")
    if not isinstance(identifier, str) or not identifier or len(identifier) > 256:
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            "The descriptor publishes no bounded artifact id.",
        )
    if not isinstance(top, str) or not top or len(top) > 256:
        raise SimraArtifactError(
            "testbench.artifact.invalid",
            "The descriptor publishes no bounded top cell name.",
        )
    label = descriptor.get("label")
    if not isinstance(label, str) or len(label) > 512:
        label = identifier

    netlist_path = _sibling(directory, descriptor.get("netlist"), field_name="netlist")
    view_path = _sibling(directory, descriptor.get("view"), field_name="view")

    if validation.get("netlistable") is not True or descriptor.get("netlistable") is not True:
        raise SimraArtifactError(
            "testbench.artifact.not_netlistable",
            "The published artifact does not claim a runnable netlist.",
        )
    # Report the actionable parameter state before the derived readiness flag:
    # Simra clears simulation_ready whenever parameters are partial, and
    # "simulation_ready=false" tells an author nothing about what to bind.
    parameters_state = validation.get("parameters")
    # Preserve the existing handoff refusal precedence for resolved artifacts.
    # A partial artifact still takes the parameter refusal, after its published
    # deck/view have supplied the actionable explanation.
    self_contained = validation.get("simulation_ready") is True
    handoff = validation.get("simulation_handoff")
    if parameters_state == "resolved" and handoff not in SUPPORTED_HANDOFFS:
        raise SimraArtifactError(
            "testbench.handoff.unsupported",
            f"The published artifact reports simulation_handoff={handoff!r}; "
            f"only {' and '.join(SUPPORTED_HANDOFFS)} are dispatchable.",
        )

    deck_text, netlist_sha256, netlist_record = _read_text_file(
        netlist_path,
        kind="spice-netlist",
        role="netlist",
        maximum_bytes=MAX_DECK_BYTES,
    )
    view_document, view_sha256, view_record = _read_json_document(
        view_path,
        role="schematic-view",
        maximum_bytes=MAX_VIEW_BYTES,
    )

    published_netlist_sha = hashes.get("netlist_sha256")
    published_view_sha = hashes.get("view_sha256")
    if published_netlist_sha != netlist_sha256:
        raise SimraArtifactError(
            "testbench.artifact.digest_mismatch",
            f"{netlist_path} hashes to {netlist_sha256} but the descriptor publishes "
            f"{published_netlist_sha!r}.",
        )
    if published_view_sha != view_sha256:
        raise SimraArtifactError(
            "testbench.artifact.digest_mismatch",
            f"{view_path} hashes to {view_sha256} but the descriptor publishes "
            f"{published_view_sha!r}.",
        )
    source_sha256 = hashes.get("source_sha256")
    if not isinstance(source_sha256, str) or len(source_sha256) != 64:
        source_sha256 = ""

    if view_document.get("schema") != VIEW_SCHEMA:
        raise SimraArtifactError(
            "testbench.artifact.unsupported_schema",
            f"Expected a {VIEW_SCHEMA} view, got {view_document.get('schema')!r}.",
        )

    # Simra publishes the exact missing parameter names in the deck and the
    # owning instance/cell/source location in the typed view. Read and
    # digest-check both before refusing so the author sees what and where to
    # edit, without echoing the descriptor's absolute host location.
    unresolved = _unresolved_placeholders(deck_text, top_cell=top)
    if parameters_state != "resolved" or unresolved:
        message, hint = _unresolved_parameter_diagnostic(
            parameters_state=parameters_state,
            unresolved=unresolved,
            view_document=view_document,
            descriptor_source=descriptor.get("source"),
        )
        raise SimraArtifactError(
            "testbench.parameters.unresolved",
            message,
            hint=hint,
        )

    # ``simulation_ready`` is narrower than its name suggests: Simra clears it
    # for every testbench containing a MOS instance, because model collateral is
    # deliberately outside the schematic contract. It therefore means "runs with
    # no external collateral", not "is fit to simulate". Carry it as a fact and
    # let the operation decide whether the caller supplied the missing models.

    testbench = view_document.get("testbench")
    if not isinstance(testbench, Mapping):
        raise SimraArtifactError(
            "testbench.declaration.missing",
            "The published view carries no typed testbench declaration.",
        )
    declared = testbench.get("analyses")
    if not isinstance(declared, list) or not declared:
        raise SimraArtifactError(
            "testbench.declaration.missing",
            "The published testbench declares no analyses.",
        )
    if len(declared) > MAX_ANALYSES:
        raise SimraArtifactError(
            "testbench.analyses.over_limit",
            f"The published testbench declares {len(declared)} analyses; "
            f"the bounded ceiling is {MAX_ANALYSES}.",
        )
    analyses = tuple(
        _typed_analysis(entry, position) for position, entry in enumerate(declared)
    )
    if (handoff == "direct") != (len(analyses) == 1):
        raise SimraArtifactError(
            "testbench.handoff.inconsistent",
            f"simulation_handoff={handoff!r} disagrees with {len(analyses)} declared analyses.",
        )

    saved = testbench.get("save", [])
    if not isinstance(saved, list) or len(saved) > MAX_SAVED_NETS:
        raise SimraArtifactError(
            "testbench.declaration.invalid",
            "The published testbench save list is missing or unbounded.",
        )
    saved_nets: list[str] = []
    for name in saved:
        if not isinstance(name, str) or _NET_NAME_RE.fullmatch(name) is None:
            raise SimraArtifactError(
                "testbench.declaration.invalid",
                "The published testbench save list contains an unbounded net name.",
            )
        saved_nets.append(name)

    return SimraTestbench(
        descriptor_path=Path(descriptor_record["path"]),
        directory=directory,
        identifier=identifier,
        label=label,
        top=top,
        netlist_path=Path(netlist_record["path"]),
        view_path=Path(view_record["path"]),
        analyses=analyses,
        saved_nets=tuple(saved_nets),
        simulation_handoff=handoff,
        parameters_state=parameters_state,
        self_contained=self_contained,
        netlist_sha256=netlist_sha256,
        view_sha256=view_sha256,
        source_sha256=source_sha256,
        deck_text=deck_text,
        input_records=(descriptor_record, netlist_record, view_record),
    )


def _deck_lines(deck_text: str) -> list[str]:
    return deck_text.splitlines(keepends=True)


def load_model_prelude(
    models_file: str | Path,
    *,
    permitted_executable_models: frozenset[str] = frozenset(),
) -> tuple[str, dict[str, Any]]:
    """Return one self-contained model-card prelude and its retained record.

    A Simra deck names device models but never emits ``.include`` or ``.lib``,
    so a model-bound testbench needs its model cards supplied. The bounded
    shared simulation profile accepts no include directive, so the prelude must
    itself be self-contained; a hierarchical PDK entry file is refused rather
    than silently escalated to an uninspected include chain.

    Self-contained also means no card reaching outside the deck through an
    XSPICE code model: any ``.model`` whose type is in
    :data:`EXECUTABLE_MODEL_TYPES` is refused unless its exact (case-folded)
    name is listed in ``permitted_executable_models`` -- the closed set of
    binding cards a reviewed, digest-pinned block composition generated. The
    caller that passes the set MUST also pin the composition digest, so the
    permitted names can only ever bind the reviewed bytes.
    """

    path = Path(models_file).expanduser()
    if not path.is_absolute():
        raise SimraArtifactError(
            "configuration.models.invalid",
            f"The model-library locator must be an absolute path: {path}",
        )
    text, _digest, record = _read_text_file(
        path,
        kind="spice-model-library",
        role="model-library",
        maximum_bytes=MAX_MODELS_BYTES,
    )
    for number, line in enumerate(text.splitlines(), start=1):
        if MODELS_FORBIDDEN_RE.match(line):
            raise SimraArtifactError(
                "configuration.models.not_self_contained",
                f"{path}:{number} declares a directive this bounded profile cannot accept: "
                f"{line.strip()[:120]}",
                hint=(
                    "Supply a flattened self-contained model card set. A hierarchical PDK "
                    "entry file with .include or .lib is outside testbench.simulate/v1alpha1."
                ),
            )
    # Executable/file-backed code models are scanned over CONTINUATION-JOINED
    # statements: `.model x\n+ d_cosim(...)` is the same card as one line.
    statements: list[tuple[int, str]] = []
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if stripped.startswith("+") and statements:
            first, body = statements[-1]
            statements[-1] = (first, body + " " + stripped[1:].strip())
            continue
        statements.append((number, line))
    for number, statement in statements:
        card = _MODEL_CARD_RE.match(statement)
        if card is None:
            continue
        model_type = card.group("type").lower()
        if model_type not in EXECUTABLE_MODEL_TYPES:
            continue
        model_name = card.group("name").lower()
        # The allowance is name AND type exact: the only card a reviewed block
        # composition ever generates is a d_cosim binding, so a permitted name
        # can never be reused to admit a process- or file-backed model.
        if model_type == PERMITTED_EXECUTABLE_MODEL_TYPE and (
            model_name in permitted_executable_models
        ):
            continue
        raise SimraArtifactError(
            "configuration.models.executable_model",
            f"{path}:{number} declares a {model_type} model card; this XSPICE "
            "code model reaches outside the deck (an executable object, a "
            "process, or a file) and is outside the self-contained "
            "model-library role.",
            hint=(
                "Executable code models are only accepted as the generated, "
                "digest-pinned binding cards of a reviewed block composition "
                "(openada simulate --blocks ... --cosim)."
            ),
        )
    if not text.endswith("\n"):
        text += "\n"
    return text, record


def derive_single_analysis_decks(
    testbench: SimraTestbench,
    *,
    model_prelude: str | None = None,
) -> tuple[DerivedDeck, ...]:
    """Split one published deck into exactly one deck per declared analysis.

    The published deck's ordered top-level analysis cards must correspond
    one-to-one with the typed ``testbench.analyses`` declaration. Every other
    line, including the title, subcircuit definitions, sources, ``.SAVE``, and
    ``.END``, is carried through byte-for-byte.
    """

    lines = _deck_lines(testbench.deck_text)
    card_positions: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        # The first line of a SPICE deck is its title, never a directive; the
        # shared profile's own inspection skips it, so splitting must agree.
        if index == 0:
            continue
        match = ANALYSIS_CARD_RE.match(line)
        if match is not None:
            card_positions.append((index, match.group(1).lower()))

    declared_kinds = [analysis["kind"] for analysis in testbench.analyses]
    observed_kinds = [kind for _position, kind in card_positions]
    if observed_kinds != declared_kinds:
        raise SimraArtifactError(
            "testbench.deck.mismatch",
            "The published deck's analysis cards "
            f"({', '.join(observed_kinds) or 'none'}) do not match the typed declaration "
            f"({', '.join(declared_kinds)}).",
            hint="Recompile the testbench so the emitted deck and its declaration agree.",
        )

    prelude_lines: list[str] = []
    if model_prelude:
        prelude_lines = _deck_lines(model_prelude)

    derived: list[DerivedDeck] = []
    for selected, (position, kind) in enumerate(card_positions):
        dropped = {other for other, _kind in card_positions} - {position}
        kept: list[str] = []
        for index, line in enumerate(lines):
            if index in dropped:
                continue
            kept.append(line)
            if index == 0 and prelude_lines:
                if not line.endswith("\n"):
                    kept[-1] = line + "\n"
                kept.extend(prelude_lines)
        text = "".join(kept)
        if not text.endswith("\n"):
            text += "\n"
        derived.append(
            DerivedDeck(
                index=selected,
                kind=kind,
                analysis=dict(testbench.analyses[selected]),
                text=text,
                sha256=hashlib.sha256(text.encode("utf-8")).hexdigest(),
            )
        )
    return tuple(derived)


def deck_file_name(deck: DerivedDeck, *, total: int) -> str:
    """Return one stable, ordered, collision-free derived-deck file name."""

    width = max(2, len(str(total)))
    return f"analysis-{deck.index + 1:0{width}d}-{deck.kind}.spice"


__all__ = [
    "ANALYSIS_CARD_RE",
    "ARTIFACT_SCHEMA",
    "DerivedDeck",
    "MAX_ANALYSES",
    "MAX_CDL_BYTES",
    "MAX_DECK_BYTES",
    "MAX_DESCRIPTOR_BYTES",
    "MAX_MODELS_BYTES",
    "MAX_SOURCE_BYTES",
    "MAX_VIEW_BYTES",
    "SUPPORTED_ANALYSIS_KINDS",
    "SUPPORTED_HANDOFFS",
    "SimraArtifactError",
    "SimraSchematicBundle",
    "SimraTestbench",
    "VIEW_SCHEMA",
    "deck_file_name",
    "derive_single_analysis_decks",
    "load_model_prelude",
    "load_simra_schematic_bundle",
    "load_simra_testbench",
]
